/**
 * Predictable alternate search terms for SEC documentation pages.
 * Keyed by doc slugAsParams (without the docs/ prefix).
 */

/** Applied to every SEC doc entry in the search index. */
export const SEC_GLOBAL_SEARCH_KEYWORDS = [
  "SEC",
  "SoulslikeCombat",
  "Soulslike Enemy Combat",
  "SoulslikeEnemyCombat",
  "Unreal Engine",
  "UE5",
  "enemy AI",
  "combat AI",
  "plugin",
  "Fab",
  "marketplace",
];

/** Per-page alternate terms. Merged with global keywords at build time. */
export const SEC_DOC_SEARCH_KEYWORDS: Record<string, string[]> = {
  SoulslikeCombatDocs: [
    "overview",
    "documentation",
    "systems",
    "full docs",
    "index",
    "home",
  ],
  "soulslike-combat/getting-started": [
    "install",
    "installation",
    "setup",
    "quick start",
    "first enemy",
    "demo",
    "dependencies",
    "GameplayAbilities",
    "StateTree",
    "MotionWarping",
    "EnemyCharacterBase",
    "EnemyControllerBase",
    "AIConfig",
    "ActionSet",
    "beginner",
    "tutorial",
  ],
  "soulslike-combat/architecture": [
    "mental model",
    "controller",
    "pawn",
    "StateTree",
    "Behavior Tree",
    "BT",
    "hybrid",
    "decision",
    "execution",
    "SECCombatControllerComponent",
    "brain",
    "pipeline",
    "server",
    "replication",
  ],
  "soulslike-combat/step-by-step-enemy": [
    "create enemy",
    "build enemy",
    "weapon",
    "combo",
    "moveset",
    "ActionSpec",
    "ability",
    "GA_",
    "melee",
    "tutorial",
    "walkthrough",
    "from scratch",
  ],
  "soulslike-combat/movement-system": [
    "strafe",
    "strafing",
    "navmesh",
    "nav mesh",
    "detour",
    "pathfinding",
    "path find",
    "hybrid movement",
    "tactical",
    "strategic",
    "distance",
    "positioning",
    "MovementEvaluatorComponent",
    "bDetourUseLineOfSightPreGate",
    "line of sight pre-gate",
    "LOS pre-gate",
    "gap",
    "pit",
    "ledge",
    "corner",
    "cover",
    "approach blocked",
    "HybridSwitchDistance",
    "avoidance",
    "stuck",
    "STTask_AIMovement",
  ],
  "soulslike-combat/action-system": [
    "ActionEvaluationComponent",
    "ActionSet",
    "ActionSpec",
    "utility",
    "scoring",
    "cooldown",
    "chain",
    "chaining",
    "STTask_PollAction",
    "STTask_DoAction",
    "SEC.Action.End",
    "SEC.Action.Start",
    "ability",
    "attack selection",
    "novelty",
    "weight",
  ],
  "soulslike-combat/reaction-system": [
    "ReactionEvaluationComponent",
    "ReactionSet",
    "ReactionSpec",
    "parry",
    "dodge",
    "counter",
    "block",
    "event driven",
    "priority",
    "SEC.Reaction",
    "hit react",
    "defensive",
  ],
  "soulslike-combat/combat-roles": [
    "AICombatRoleSubsystem",
    "Attacker",
    "Flanker",
    "Waiter",
    "Supporter",
    "Elite",
    "SEC.Role",
    "multi enemy",
    "coordination",
    "slot",
    "fitness",
    "role sync",
    "pack",
    "swarm",
  ],
  "soulslike-combat/threat-detection": [
    "ThreatDetectionComponent",
    "camera",
    "looking at",
    "attention",
    "threat level",
    "player focus",
    "aware",
  ],
  "soulslike-combat/awareness-system": [
    "SECAwarenessComponent",
    "perception",
    "sight",
    "hearing",
    "investigate",
    "detected",
    "suspicious",
    "last known location",
    "STCondition_AwarenessState",
    "STTask_PollLastKnownLocation",
    "stealth",
    "forget",
  ],
  "soulslike-combat/melee-trace": [
    "SECMeleeTraceComponent",
    "hit detection",
    "weapon trace",
    "sweep",
    "damage",
    "ISECDamageable",
    "USECDamageConfig",
    "notify state",
    "hitbox",
    "socket",
  ],
  "soulslike-combat/targeting-system": [
    "TargetSelector",
    "AICombatRoleSubsystem",
    "focus actor",
    "target pool",
    "team filter",
    "orphan",
    "multi target",
    "STTask_PollFocusActor",
    "aggro",
  ],
  "soulslike-combat/configuration": [
    "EnemyAIConfig",
    "UActionSet",
    "UReactionSet",
    "MovementBehaviorProfile",
    "data asset",
    "role profile",
    "settings",
    "reference",
    "UPROPERTY",
    "tuning",
  ],
  "soulslike-combat/statetree": [
    "StateTree",
    "GameplayStateTree",
    "STTask",
    "STCondition",
    "BotStateTreeAIComponent",
    "graph",
    "native brain",
    "SECBrainComponent",
    "STTask_BuildDecisionContext",
  ],
  "soulslike-combat/multiplayer": [
    "dedicated server",
    "listen server",
    "replication",
    "replicated",
    "server authoritative",
    "network",
    "client",
    "ASC",
  ],
  "soulslike-combat/performance": [
    "stat SEC",
    "profiling",
    "cost",
    "tick budget",
    "crowd",
    "many enemies",
    "optimization",
    "CPU",
    "scalability",
  ],
  "soulslike-combat/troubleshooting": [
    "debug",
    "console variable",
    "CVar",
    "SEC.Debug",
    "FAQ",
    "not working",
    "broken",
    "fix",
    "error",
    "LogMovementEvaluator",
    "LogEvaluation",
  ],
  "soulslike-combat/api-reference": [
    "C++",
    "Blueprint",
    "API",
    "SECCombatControllerComponent",
    "EnemyControllerBase",
    "SECBrainComponent",
    "function",
    "delegate",
    "interface",
  ],
  "soulslike-combat/patterns": [
    "examples",
    "melee enemy",
    "defensive enemy",
    "aggressive enemy",
    "template",
    "recipe",
    "archetype",
    "preset",
  ],
};
